"""LLM-proposed risk management factors.

These were generated by LLM backtest diagnosis of factor strategy weaknesses:
- market_risk_off: avoid opening positions when the overall market is declining
- drawdown_stop_gap: avoid buying stocks in deep drawdowns
- volume_surge_confirm: require volume expansion on breakout signals
"""

import numpy as np
import pandas as pd

from factor.base import Factor, FactorMeta
from factor.registry import register_factor


@register_factor
class MarketRiskOff(Factor):
    """Fraction of last 20 days the market (equal-weighted) closed below its 60d MA.

    When >0.5, the market is in a sustained downtrend — risk-off environment.
    Same value for all stocks on a given day (cross-sectionally uniform),
    so the factor acts as a market-regime gate via its calibrated weight.
    """

    meta = FactorMeta(
        name="market_risk_off",
        category="risk",
        description="Fraction of last 20 days market close < 60d MA (risk-off indicator)",
        lookback_days=60,
    )

    @property
    def required_fields(self) -> list[str]:
        return ["close"]

    def compute(self, data: pd.DataFrame) -> pd.Series:
        close = data["close"].unstack()
        # Market = equal-weighted average close
        mkt_close = close.mean(axis=1)
        mkt_ma60 = mkt_close.rolling(window=60).mean()
        mkt_below = (mkt_close < mkt_ma60).astype(float)
        risk_off = mkt_below.rolling(window=20).sum() / 20.0
        # Broadcast to all stocks
        result = pd.DataFrame(
            {sym: risk_off for sym in close.columns},
            index=close.index,
        )
        result.index.name = "trade_date"
        result.columns.name = "symbol"
        return result.stack().sort_index()


@register_factor
class DrawdownStopGap(Factor):
    """How far current close is below the 20-day highest high.

    (ts_max(high, 20) - close) / ts_max(high, 20)
    0 = at recent high; 0.15 = 15% below recent high (deep gap, avoid buying).
    Uses high (not close) for the peak to catch intraday spikes that failed.
    """

    meta = FactorMeta(
        name="drawdown_stop_gap",
        category="risk",
        description="Gap from 20-day highest high to current close (deep gap = avoid)",
        lookback_days=20,
    )

    @property
    def required_fields(self) -> list[str]:
        return ["close", "high"]

    def compute(self, data: pd.DataFrame) -> pd.Series:
        close = data["close"].unstack()
        high = data["high"].unstack()
        high_20 = high.rolling(window=20, min_periods=10).max()
        gap = (high_20 - close) / (high_20 + 1e-10)
        return gap.stack().sort_index()


@register_factor
class VolumeSurgeConfirm(Factor):
    """Today's volume / 20-day average volume — raw daily surge.

    Unlike VolumeSurge5D (which uses 5d avg / 20d avg, smoother), this
    captures the exact-day volume spike to confirm breakout authenticity.
    """

    meta = FactorMeta(
        name="volume_surge_confirm",
        category="leader",
        description="Today volume / 20-day avg volume (single-day surge confirmation)",
        lookback_days=20,
    )

    @property
    def required_fields(self) -> list[str]:
        return ["volume"]

    def compute(self, data: pd.DataFrame) -> pd.Series:
        volume = data["volume"].unstack()
        vol_20 = volume.rolling(window=20).mean()
        result = volume / (vol_20 + 1e-10)
        return result.stack().sort_index()
